Students = {'Student_1': {'Current Grade': 60, 
                         'Name': 'Luke', 
                         'Student Email': 'student1@gmail.com', 
                         'Assignments': {'Assignment 1': 45, 'Assignment 2' : 50, 'Assignment 3' : 75, 'Assignment 4' : 90, 'Assignment 5' : 55}, 
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '12',
                         'Advisor': 'advisor1', 
                         'Advisor Email': 'advisor1@gmail.com'}, 
            'Student_2': {'Current Grade': 67, 
                         'Name': 'Ben', 
                         'Student Email': 'student1@gmail.com', 
                         'Assignments': {'Assignment 1': 60, 'Assignment 2' : 50, 'Assignment 3' : 85, 'Assignment 4' : 80, 'Assignment 5' : 60}, 
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '9',
                         'Advisor': 'advisor1', 
                         'Advisor Email': 'advisor1@gmail.com'},
            'Student_3': {'Current Grade': 70, 
                         'Name': 'Darius', 
                         'Student Email': 'student1@gmail.com', 
                         'Assignments': {'Assignment 1': 70, 'Assignment 2' : 70, 'Assignment 3' : 75, 'Assignment 4' : 90, 'Assignment 5' : 45}, 
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '7',
                         'Advisor': 'advisor1', 
                         'Advisor Email': 'advisor1@gmail.com'},
            'Student_4': {'Current Grade': 68, 
                         'Name': 'Bergas', 
                         'Student Email': 'anargya01@allegheny.edu', 
                         'Assignments': {'Assignment 1': 65, 'Assignment 2' : 70, 'Assignment 3' : 75, 'Assignment 4' : 80, 'Assignment 5' : 50}, 
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '8',
                         'Advisor': 'advisor1', 
                         'Advisor Email': 'advisor1@gmail.com'},
            'Student_5': {'Current Grade': 74, 
                         'Name': 'Makell', 
                         'Student Email': 'student1@gmail.com', 
                         'Assignments': {'Assignment 1': 85, 'Assignment 2' : 50, 'Assignment 3' : 85, 'Assignment 4' : 90, 'Assignment 5' : 65}, 
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '13',
                         'Advisor': 'advisor1', 
                         'Advisor Email': 'advisor1@gmail.com'}
           }




