Students = {'Superuser': {'Total': 100,
                         'Name': 'Superuser',
                         'Student Email': 'student1@gmail.com',
                         'Assignments': {'Assignment 1': 45, 'Assignment 2' : 50, 'Assignment 3' : 75, 'Assignment 4' : 90, 'Assignment 5' : 55},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '12',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'advisor1@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'professor1@gmail.com'},
            'Student_1': {'Total': 67,
                         'Name': 'Ben',
                         'Student Email': 'student0@gmail.com',
                         'Assignments': {'Assignment 1': 60, 'Assignment 2' : 50, 'Assignment 3' : 85, 'Assignment 4' : 80, 'Assignment 5' : 60},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '9',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'advisor1@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'professor1@gmail.com'},
            'Student_2': {'Total': 70,
                         'Name': 'Darius',
                         'Student Email': 'student1@gmail.com',
                         'Assignments': {'Assignment 1': 70, 'Assignment 2' : 70, 'Assignment 3' : 75, 'Assignment 4' : 90, 'Assignment 5' : 45},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '7',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'advisor1@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'professor1@gmail.com'},
            'Student_3': {'Total': 68,
                         'Name': 'Bergas',
                         'Student Email': 'anargya01@allegheny.edu',
                         'Assignments': {'Assignment 1': 65, 'Assignment 2' : 70, 'Assignment 3' : 75, 'Assignment 4' : 80, 'Assignment 5' : 50},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '8',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'bergaspurboyo@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'bergasbatara@yahoo.com'},
            'Student_4': {'Total': 74,
                         'Name': 'Makell',
                         'Student Email': 'student1@gmail.com',
                         'Assignments': {'Assignment 1': 85, 'Assignment 2' : 50, 'Assignment 3' : 85, 'Assignment 4' : 90, 'Assignment 5' : 65},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '13',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'advisor1@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'professor1@gmail.com'},
            'Student_5': {'Total': 65,
                        'Name': 'Luke',
                        'Student Email': 'student5@gmail.com',
                         'Assignments': {'Assignment 1': 75, 'Assignment 2' : 48, 'Assignment 3' : 65, 'Assignment 4' : 72, 'Assignment 5' : 65},
                         'Assigned Class': 'CMPSC 300',
                         'Days Missed': '13',
                         'Advisor': 'advisor1',
                         'Advisor Email': 'advisor1@gmail.com',
                         'Professor': 'Professor Bonham-Carter',
                         'Professor Email': 'professor1@gmail.com'
            }
           }


# print(Students['Student_1'])



