Students = {Superuser_Student: {Email: student1@gmail.com,
                         Advisor: advisor1,
                         Advisor_Email: advisor1@gmail.com,
                         total: 100},
            Student_2: {Email: student2@gmail.com,
                         Advisor: advisor2,
                         Advisor_Email: advisor2@gmail.com,
                         total: 71},
            Student_3: {Email: student3@gmail.com,
                         Advisor: advisor3,
                         Advisor_Email: advisor3@gmail.com,
                         total: 50},
            Student_4: {Email: student4@gmail.com,
                         Advisor: advisor4,
                         Advisor_Email: advisor4@gmail.com,
                         total: 85}
           }
